### ISSUE TITLE
Failed to save text

### ISSUE THREAD

**Issue by 1aozhang** [stephenmelnicki/denopaste#1]
Hi 

I tried deno_paste on Deno Deploy with the SUPABASE_URL and SUPABASE_KEY all set via environment variables,
but got error msg like "Failed to save text. Please try again." when I clicked on "paste".

According to the log:
Error: relation "public.entries" does not exist
    at Database.insertEntry (file:///src/utils/database.ts:15:19)
    at async POST (file:///src/routes/index.tsx:18:13)
    at async https://deno.land/x/rutt@0.0.13/mod.ts:112:36
    at async Server.#respond (https://deno.land/std@0.150.0/http/server.ts:219:24)

I there anything I've missed? Maybe I need to create tables in the database in advance to get the app prepared?

Best regards.

**Comment by 1aozhang** [comment]
Hi 

Just figured it out by looking into the database.ts and I should have created a table "entries" in advance in supabase

with two text columns, id and contents.

Then everything works fine now.

Thanks and regards.

**Comment by stephenmelnicki** [comment]
@1aozhang My apologies for the late reply! Only just saw your issue a moment ago.

I'm glad you were able to resolve it on your own. I'll update the `README.md` to include some instructions concerning the table name, columns and types for anyone else who comes along in the future.

Thanks for submitting the issue!
